### PR TITLE
Add support ZF3

### LINKED ISSUE #61: Installation with new ZendSkeletonApplication installs all components
When I install BjyProfiler with the new ZendSkeletonApplication and Zend\Mvc 3 all ZF components are installed. Even Barcode and Captcha. I have no idea why this happens but it should be solved.

### PR DESCRIPTION
**Pull request by andrey-mokhov**
Fixed: #61 Installation with new ZendSkeletonApplication installs all components

### CODE REVIEW

**Comment by robob4him** [comment]
Is there a status with this?

**Comment by andrey-mokhov** [comment]
This patch allow use db profiler with ZF3

**Comment by criterion9** [comment]
How do we get this added to master? Is anyone maintaining this?

**Comment by ikovalyov** [comment]
any update?

**Comment by andrey-mokhov** [comment]
@robob4him, @criterion9, @ikovalyov 
Sorry for my bad english.

I fork this module and patch him. For use this module in ZF3 with my changes, use:
```console
composer require andrey-mokhov/bjy-profiler:dev-master
```

**Comment by andrey-mokhov** [comment]
Released  version 1.3.0

[See changes](https://github.com/andrey-mokhov/bjy-profiler/releases/tag/1.3.0)

```console
$ composer require --dev andrey-mokhov/bjy-profiler:^1.3
```

**Pull request closed without merging**
